# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# os
os:
  - linux
# Set the python version to 3.6, 3.7
python:
  - "3.6"
  - "3.7"

# Install the pip dependency
install:
  - pip install transformers
  - pip install sentencepiece

# Run the unit test
script:
  - python tests.py
  # - coverage run tests.py
